
    /*     
    *   This file is automatically generated.
    *   Change it freely to change your build configuration.
    *   To rebuild this file, delete it and rerun build.
    */
    ({
    'app.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'main.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'routes.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'sys/extensions.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'sys/model.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'sys/router.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'sys/template-helpers.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'sys/template.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'sys/view-manager.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'templates/layout.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'templates/navigation.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/di/class-module.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/di/injected/custom-module1.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/di/injected/custom-module2.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/di/injected/template.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/di/object-module.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/di/template.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/model-binding/declarative.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/model-binding/programmatic.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/remote-data-example/data.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/remote-data-example/framework-details.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/dynamic-data/remote-data-example/frameworks.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/home.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/_default.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/class-module-change-element.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/class-module-element-manipulation.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/class-module-simple.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/events-handlings.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/module-plain-text-template.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/module-plain-text.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/object-module-change-element.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/object-module-element-manipulation.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/object-module-simple.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/modules/view-events.js': {
        minify: true,
        minifyEngine: "uglify-es",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/not-found.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/composite/template1.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/composite/template2.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/composite/template3.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/composite/template4.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/composite/template5.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/composite/template6.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/parameterized-sub-route.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/parameterized.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/plain-text-view.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    },
    'views/templates/state-view.html': {
        minify: true,
        minifyEngine: "html-minifier",
        minifyJsOptions: null,
        minifyEsOptions: null,
        htmlMinifierOptions: {
            minifyJS: true,
            minifyCSS: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            collapseWhitespace: true
        }
    }
})