
    /*     
    *   This file is automatically generated.
    *   Change it freely to change your build configuration.
    *   To rebuild this file, delete it and rerun build.
    */
    ({
    'bootstrap.css': {
        minify: true
    },
    'default.css': {
        minify: true
    },
    'navigation.css': {
        minify: true
    }
})