
    /*     
    *   This file is automatically generated.
    *   Change it freely to change your build configuration.
    *   To rebuild this file, delete it and rerun build.
    */
    ({
    'require.js': {
        minify: true,
        minifyEngine: "uglify-js"
    },
    'text.js': {
        minify: true,
        minifyEngine: "uglify-js"
    }
})