define([
    "e-Element/find",
    "e-Element/forEachChild",
    "e-Element/show",
    "e-Element/hide",
    "e-Element/appendTo",
    "e-Element/on",
    "e-Element/html",
    "e-String/hashCode",
    "e-String/createElement",
    "e-String/html"
]);
